### ISSUE TITLE
Dependencies and versioning

### ISSUE THREAD

**Issue by adamstyrc** [handstandsam/ShoppingApp#22]
First of all, wanted to say "Great work!" :)

Maybe it's wrong place but I wanted to ask how is the `Dependencies.kt` wired across whole project ? When I try to do the same in my project, using either object **Versions** or **Libs** is not recognised in modules `build.gradle`. 

How to set these variables visibility ?

**Comment by handstandsam** [comment]
Sorry for the late response.  Hopefully you have figured out by now, if not, let me know by reopening.
