### ISSUE TITLE
doesn't build 

### ISSUE THREAD

**Issue by chingchongdev** [handstandsam/ShoppingApp#23]
ERROR: Plugin [id: 'org.gradle.kotlin.kotlin-dsl', version: '1.2.8'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'org.gradle.kotlin.kotlin-dsl:org.gradle.kotlin.kotlin-dsl.gradle.plugin:1.2.8')
  Searched in the following repositories:
    Gradle Central Plugin Repository

**Comment by handstandsam** [comment]
Should be working now after some updates. Let me know if you have any other issues!
