### ISSUE TITLE
logo for ShoppingApp

### ISSUE THREAD

**Issue by hafizahmmed** [handstandsam/ShoppingApp#4]
Hello,
Good Day, i make a logo icon for your project. If you want to use this logo in your project, then comment below, I will give you the source file. And if you want a change, then tell me I will change.It's totally free for open source project. I make this is a shopping cart. which color you need comment below. then i make a pull request.

![shoppingapp-01](https://user-images.githubusercontent.com/38810169/42502141-16f03c60-8457-11e8-865c-8f0c8b3cda8b.jpg)

**Comment by handstandsam** [comment]
@hafizahmmed !!! This is awesome!  I love it.  I'm going to throw in the blue one for now, but would love a PR with a better asset.  Thanks so much.  I'm really sorry that I didn't se this until now!

**Comment by handstandsam** [comment]
Thanks!  Open a PR with any logo changes like this.  They are great!  Closing this issue since I added your logo here: https://github.com/handstandsam/ShoppingApp/pull/11
